services:
  frontend:
    build:
      context: .
      args:
        - VITE_APP_ENV=${NODE_ENV:-production}
        - VUE_BASE_URL=${VUE_BASE_URL}
        - VUE_API_BASE_URL=${VUE_API_BASE_URL}
    ports:
      - "${PORT:-4321}:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./nginx/logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ot-network

networks:
  ot-network:
    external: true