version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:1234 --workers 3 --threads 2
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 1234
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - ot-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    networks:
      - ot-network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "1234:80"
    depends_on:
      - web
    networks:
      - ot-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  ot-network:
    driver: bridge